<?php

class TemplateController extends ApplicationController {
    public function indexAction() {
    }

    public function layoutAction() {
    }

    public function placeAction() {
    }

    public function inflateTextAction() {
    }

    public function inflateTextPlaceAction() {
    }

    public function inflateProcAction() {
    }

    public function inflateProcPlaceAction() {
    }

    public function inflateProcOptPlaceAction() {
    }

    public function inflateProcCacheAction() {
    }

    public function inflateFileAction() {
    }

    public function inflateFilePlaceAction() {
    }

    public function helperAction() {
    }

    public function formAction() {
    }
}