<?php
/**
 * application.inc 提供MVC前端应用控制器声明。
 *
 * @copyright 2012-2013 Skihat team (skihat.cn)
 * @license   http://skihat.cn/license.html
 * @author    Skihat Team
 *
 * @package   skihat.appservs
 * @version   1.0
 *
 * @created   2012-07-23
 * @modified  2013-08-13
 */

# 引用应用基础类。
Skihat::import('applications.application_base', SKIHAT_PATH_LIBRARY);

/**
 * 应用前端控制器类，处理应用请求可关服务。
 *
 * @package skihat.appservs
 */
class Application extends ApplicationBase {

}